### PR TITLE
feat: support using {file} placeholder multiple times in command

### LINKED ISSUE #16: [Feature]: enable the ability to use {file} placeholder multiple times in command setting
### Current behavior

Only first `{file}` in setting `AkiraVoid.formatWithCLI.command` will be replaced to the path to formatting document, other placeholders will be ignored.

### Expected behavior

All placeholders should be recognized and replaced.

### Other contexts

This feature is originally discussed in #14

### PR DESCRIPTION
**Pull request by AkiraVoid**
* support using {file} placeholder multiple times in command

Close #14 , #16

### CODE REVIEW

**Comment by dhananjaipai** [comment]
One implementation suggestion is to change the implementation for performance improvement (without using the writeFileSync to cacheFile may be as below

Replace line :83 from
` const command = getCommand(doc.languageId).replace('{file}', cacheFile); ` to be based on whether cacheFile is enabled or not (using an additional flag).

If cacheFile is not enabled (and you want to do it through stdout), you could do
`` const command = `echo  '${content}' | getCommand(doc.languageId).replaceAll('{file}', doc.fileName)` ``
This will pipe the content into the command through stdin and the command just has to be `prettier --stdin-filepath {file}` we will still need the file since prettier uses the file extension to identify the type I am assuming.


`cat ${file} | command` does not technically offer any performance advantage since the command should read from the file anyway, which I think is just better if the formatter reads by itself.

with `echo ''` however, we can avoid the fileWrite altogether and  I believe it should be compatible in both Powershell and Bash, since powershell has it aliased.

**Comment by AkiraVoid** [comment]
@dhananjaipai sorry for the late response. I'm working on my full-time job, and I can hardly do any further works on this project in my weekdays. May the new version could be released this weekend, thanks for your patience.

**Comment by dhananjaipai** [comment]
No worries!
As a matter of fact, I learned a lot about VSCode extensions and development, and Github in general learning from your source code - and really liked how you created the akiravoid-bot, the awesome semantic-release setup you had and even the Github actions that automated things end to end!
I actually created a fork to test out some of the things I suggested, and yeah `echo ''` was a bad idea, since it would mess things up if the contents have a `'` in them !

I had created a fork from this repo, but ended up rewriting it in javascript, since typescript for some reason was too slow for me from a dev environment perspective with the recompiling. And yeah, apparently the "Debugger" environment makes things a loooooot slower than when the extension runs on installation, which kind of makes sense.

I ended up adding support for all the 4 modes we discussed - the direct mode and 3 modes for doing it in the editor based on how inputs and outputs will be parsed.

I have added you to credits https://github.com/dhananjaipai/vscode-faster-format-with-cli?tab=readme-ov-file#credits  and as a contributor in the package json too!

The `settings.json` issue with editor.formatOnSave was particularly annoying to recover from, and I actually removed support for `jsonc` language as a temporary fix.

[Do take a look](https://marketplace.visualstudio.com/items?itemName=djpai.faster-format-with-cli) when you have some time!

**Comment by AkiraVoid** [comment]
@dhananjaipai I've seen your approach, and it is great, but I finally decided not to add it as a feature. First of all, the echo-like solution is the most efficient one but it's hard to solve the differences of all platforms. I don't know how to send a string with line-breaks to stdout on Windows, without read the file. So it seems the cat solution is the only way left. But, as our extension's formatting command is highly customizable, users can use cat by their own, and we don't need to specifically "support" it.

**Pull request merged**
